name: lz-management-tst

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/tmp-landingzone.yml
    with:
      topLevelManagementGroupName: gazelle
      environment: tst
      location: westeurope
      parameterFile: ./landingzones/parameters/cis-management-tst.json
    secrets: inherit