name: lz-paltform-management-tst

on:
  workflow_dispatch:
  push:
    paths:
      - './landingzones/parameters/platform-management-tst.json'

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/tmp-landingzone.yml
    with:
      topLevelManagementGroupName: gazelle
      environment: tst
      location: francecentral
      parameterFile: ./landingzones/parameters/platform-management-tst.json
    secrets: inherit