name: lz-platform-management-prod

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  landingzone:
    uses: ./.github/workflows/tmp-landingzone.yml
    with:
      topLevelManagementGroupName: gazelle
      environment: prod
      location: francecentral
      parameterFile: ./landingzones/parameters/platform-management-prod.json
    secrets: inherit