name: managementGroups

on:
  push:
    branches:
      - tst/**
  
  workflow_dispatch:

  pull_request:
    types: 
      - closed

permissions:
  id-token: write
  contents: read

jobs:
  linter:
    if: startsWith(github.ref, 'refs/heads/tst/') 
    uses: ./.github/workflows/reuse-linter.yml
    with:
      bicepFilePath: ./managementGroups/bicep-main/managementGroups.bicep

  tst:
    needs: linter
    if: startsWith(github.ref, 'refs/heads/tst/') 
    uses: ./.github/workflows/reuse-managementGroup.yml
    secrets: inherit

  prod:
    needs: tst
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/reuse-managementGroup.yml
    secrets: inherit

