name: managementGroups

env:
  mainBicepFile: ./managementGroups/bicep-main/managementGroups.bicep

on:
  push:
    branches:
      - tst/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  linter: 
    uses: ./.github/workflows/reuse-linter.yml
    with:
      bicepFilePath: ./managementGroups/bicep-main/managementGroups.bicep

  tst:
    needs: linter
    uses: ./.github/workflows/reuse-managementGroup.yml
    with:
      template-file: $mainBicepFile


  prod:
    needs: tst
    uses: ./.github/workflows/reuse-managementGroup.yml
    with:
      template-file: $mainBicepFile

