name: managementGroups

on:
  push:
    branches:
      - tst/**
    # paths:
    #   - 'managementGroups/**'

  pull_request:
    branches:
      - main
    # paths:
    #   - 'managementGroups/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  linter: 
    uses: ./.github/workflows/reuse-linter.yml
    with:
      bicepFilePath: ./managementGroups/bicep-main/managementGroups.bicep

  tst:
    needs: linter
    uses: ./.github/workflows/reuse-managementGroup.yml
    with:
      template-file: ./managementGroups/bicep-main/managementGroups.bicep
    secrets: inherit

  prod:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-managementGroup.yml
    with:
      template-file: $mainBicepFile

