name: paltform-management-tst

on:
  push:
    paths:
      - 'platformManagement/**'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  platform-management:
    uses: ./.github/workflows/tmp-subscription.yml
    with:
      location: francecentral
      templateFile: platformManagement/bicep-main/main.bicep
    secrets: inherit