name: platformManagement-tst

on:
  push:
    paths:
      - 'platformManagement/**'
  
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    platformManagement:
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
      
        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.PLATFORM_IDENTITY_CLIENT_ID}}
            tenant-id: ${{ secrets.TENANT_ID }}
            allow-no-subscriptions: true
            enable-AzPSSession: false