name: reusable - management groups

on:
  workflow_call:
    inputs:
        environment:
            required: true
            description: 'environment name'
            type: string
        name:
            required: false
            description: 'Azudre deployment name'
            type: string
            default: 'management-groups'
        location:
            required: false
            default: 'westeurope'
            description: 'location for azure resources'
            type: string
        template-file:
            required: false
            default: ./managementGroups/bicep-main/managementGroups.bicep
            description: 'bicep template file path'
            type: string
        parameters:
            required: false
            default: ./managementGroups/param/managementGroups.bicepparam
            description: 'bicep parameters file path'
            type: string
    secrets:
      PLATFORM_IDENTITY_CLIENT_ID:
        required: true
      TENANT_ID:
        required: true

jobs:
  managementGroup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: echo
        run: echo "hello world"
      
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLATFORM_IDENTITY_CLIENT_ID}}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      # - name: deploy management groups
      #   uses: azure/cli@v1
      #   with:
      #       inlineScript: |
      #         az deployment mg create \
      #          --name ${{ inputs.name }} \
      #          --location ${{ inputs.location }} \
      #          --management-group-id ${{ secrets.TENANT_ID }} \
      #          --template-file ${{inputs.template-file}} \
      #          --parameters ${{ inputs.parameters}} \
      #          --parameters environment=${{ vars.ENVIRONMENT }} \
      #          --parameters topLevelManagementGroupname=${{ vars.topLevelManagementGroupname}}
