name: reusable - management groups stack

on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        deploymentStackName:
            required: true
            type: string
        location:
            required: true
            type: string
        template-file:
            required: true
            type: string
        parameter-file:
            required: true
            type: string
        parameters:
            required: false
            type: string

jobs:
  managementGroup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLATFORM_IDENTITY_CLIENT_ID}}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: deploy management groups
        uses: azure/cli@v1
        with:
            inlineScript: |
              az stack mg create \
               --name ${{ inputs.deploymentStackName }} \
               --location ${{ inputs.location }} \
               --management-group-id ${{ secrets.TENANT_ID }} \
               --template-file ${{inputs.template-file}} \
               --parameters ${{ inputs.parameter-file }} \
               --parameters environment=${{ inputs.environment }} \
               --deny-settings-mode None \
               --delete-all true \
               --yes