name: reusable - linter

on:
  workflow_call:
    inputs:
      managementGroupsfilePath:
            required: true
            type: string
      policiesfilePath:
            required: true
            type: string
      rbacfilePath:
            required: true
            type: string

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
     
      - name: Run Bicep Linter
        uses: azure/cli@v1
        with:
          inlineScript: |
            az bicep build -f ${{ inputs.managementGroupsfilePath }}
            az bicep build -f ${{ inputs.policiesfilePath }}
            az bicep build -f ${{ inputs.rbacfilePath }}