name: reusable - management groups

on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        location:
            required: false
            default: 'westeurope'
            type: string
        managementGroupTemplatefFle:
            required: false
            default: ./managementGroups/bicep-main/managementGroups.bicep
            type: string
        managementGroupParameters:
            required: false
            default: ./managementGroups/param/managementGroups.bicepparam
            type: string
        topLevelManagementGroupName:
            required: true
            type: string
        policiesTemplatefFle:
            required: false
            default: ./managementGroups/bicep-main/policies.bicep
            type: string
        policiesParameterFile:
            required: false
            default: ./managementGroups/param/policies.bicepparam
            type: string
        rbacTemplatefFle:
            required: false
            default: ./managementGroups/bicep-main/roleAssignments.bicep
            type: string
        rbacParameterFile:
            required: false
            default: ./managementGroups/param/roleAssignments.bicepparam
            type: string

jobs:
  managementGroup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLATFORM_IDENTITY_CLIENT_ID}}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: deploy management groups
        uses: azure/cli@v1
        with:
            inlineScript: |
              az deployment mg create \
               --name management-groups \
               --location ${{ inputs.location }} \
               --management-group-id ${{ secrets.TENANT_ID }} \
               --template-file ${{inputs.managementGroupTemplatefFle}} \
               --parameters ${{ inputs.managementGroupParameters}} \
               --parameters environment=${{ inputs.environment }}

      - name: deploy policies
        uses: azure/cli@v1
        with:
            inlineScript: |
              az stack mg create \
              --name policies \
              --location ${{ inputs.location }} \
              --management-group-id ${{ inputs.topLevelManagementGroupName }} \
              --template-file ${{ inputs.policiesTemplatefFle }} \
              --parameters ${{ inputs.policiesParameterFile }} \
              --parameters environment=${{ inputs.environment }} \
              --deny-settings-mode None \
              --delete-all true \
              --yes

      - name: asign RBAC
        uses: azure/cli@v1
        with:
            inlineScript: |
              az stack mg create \
              --name RBAC \
              --location ${{ inputs.location }} \
              --management-group-id ${{ inputs.topLevelManagementGroupName }} \
              --template-file ${{ inputs.rbacTemplatefFle }} \
              --parameters ${{ inputs.rbacParameterFile }} \
              --parameters environment=${{ inputs.environment }} \
              --deny-settings-mode None \
              --delete-all true \
              --yes