name: platformManagement-tst

on:
  workflow_call:
    inputs:
        environment:
            required: true
            type: string
        location:
            required: true
            default: 'southfrance'
            type: string
        templateFile:
            required: true
            type: string
       

jobs:
    platformManagement:
      runs-on: ubuntu-latest
      environment: ${{ inputs.environment }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
      
        - name: Azure login
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.management }}
            tenant-id: ${{ secrets.TENANT_ID }}
            allow-no-subscriptions: true
            enable-AzPSSession: true
      
        - name: main bicep deployment
          uses: azure/powershell@v1
          with:
              azPSVersion: 'latest'
              inlineScript: |
                $deploymentParams = @{
                  name              = "platform-management"
                  templateFile      = "${{ inputs.templateFile }}"
                  location          = "${{ inputs.location }}"
                  environment       = "${{ inputs.environment }}"
                  denysettingsMode  = "None"
                  deleteAll         = $true
                  force             = $true
                }
                $deployment = New-AzSubscriptionDeploymentStack @deploymentParams
  