name: template - landingzone

on:
  workflow_call:
    inputs:
        topLevelManagementGroupName:
            required: true
            type: string
        environment:
            required: true
            type: string
        location:
            required: true
            type: string
        templateFile:
            default: ./landingzones/bicep-main/base.bicep
            type: string
        parameterFile:
            required: true
            type: string
        
jobs:
  landingzone:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PLATFORM_IDENTITY_CLIENT_ID}}
          tenant-id: ${{ secrets.TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: prepare Deployment
        id: prepare
        uses: azure/powershell@v1
        with:
            azPSVersion: 'latest'
            inlineScript: |
              $TemplateFileText = [System.IO.File]::ReadAllText('${{ inputs.parameterFile }}')
              $params = ConvertFrom-Json $TemplateFileText -AsHashtable
              $deploymentParams = @{
                name = "outputsFromBicep"
                Location = "westeurope"
                ManagementGroupId = "${{ format('{0}-{1}', inputs.topLevelManagementGroupName, inputs.environment) }}"
                TemplateFile = "./landingzones/bicep-main/outputs.bicep"
                Params = $params
              }
              $deployment = new-azManagementGroupDeployment @deploymentParams
              $deployment.Outputs.GetEnumerator() | ForEach-Object {
                  $key = $_.Key
                  $value = $_.Value.Value
                  write-host "$key = $value"
                  Write-Host "::set-output name=$key::$value"
              }
    
      - name: rename subscription
        uses: azure/cli@v1
        with:
            inlineScript: |
              az account subscription rename  \
                --id ${{ steps.prepare.outputsFromBicep.subscriptionId }} \
                --name ${{ steps.prepare.outputsFromBicep.subscriptionName }}
              
      - name: landing zone
        uses: azure/powershell@v1
        with:
            azPSVersion: 'latest'
            inlineScript: |
              $TemplateFileText = [System.IO.File]::ReadAllText('${{ inputs.parameterFile }}')
              $params = ConvertFrom-Json $TemplateFileText -AsHashtable
              $deploymentParams = @{
                name = "landingzone"
                Location = "westeurope"
                ManagementGroupId = "${{ format('{0}-{1}', inputs.topLevelManagementGroupName, inputs.environment) }}"
                TemplateFile = "./landingzones/bicep-main/base.bicep"
                Params = $params
              }
              $deployment = new-azManagementGroupDeployment @deploymentParams